provider:
  name: faas
  gateway: http://localhost:8080

functions:
  tensorflow:
    lang: Dockerfile
    handler: ./handler
    image: alexellis/faas-tensorflow:latest
    environment:
      TF_CPP_MIN_LOG_LEVEL: "3"
      read_timeout: "20"
      write_timeout: "20"

